// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjzz7Q0MQyaMyoCVGRJ8fXXC0emdrpt_0',
    appId: '1:161489494672:web:3d1b90fa14a53b9194ee15',
    messagingSenderId: '161489494672',
    projectId: 'vcroad-a76a1',
    authDomain: 'vcroad-a76a1.firebaseapp.com',
    storageBucket: 'vcroad-a76a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgz5W9kKxYynCsX4GeAbrGFENNCkwcHag',
    appId: '1:161489494672:android:de98de44c75cc2e994ee15',
    messagingSenderId: '161489494672',
    projectId: 'vcroad-a76a1',
    storageBucket: 'vcroad-a76a1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7jps3S-CaW07ds2jK4_RDjJq-ipHS_Mg',
    appId: '1:161489494672:ios:f774901c5cd2f77b94ee15',
    messagingSenderId: '161489494672',
    projectId: 'vcroad-a76a1',
    storageBucket: 'vcroad-a76a1.firebasestorage.app',
    iosBundleId: 'com.example.vcroad',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7jps3S-CaW07ds2jK4_RDjJq-ipHS_Mg',
    appId: '1:161489494672:ios:f774901c5cd2f77b94ee15',
    messagingSenderId: '161489494672',
    projectId: 'vcroad-a76a1',
    storageBucket: 'vcroad-a76a1.firebasestorage.app',
    iosBundleId: 'com.example.vcroad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjzz7Q0MQyaMyoCVGRJ8fXXC0emdrpt_0',
    appId: '1:161489494672:web:2701e73c4cf290a994ee15',
    messagingSenderId: '161489494672',
    projectId: 'vcroad-a76a1',
    authDomain: 'vcroad-a76a1.firebaseapp.com',
    storageBucket: 'vcroad-a76a1.firebasestorage.app',
  );
}
