// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtsj7f5QCvU-aKQhdQB2RBGyZ_iE0lFa8',
    appId: '1:1010169881408:web:af8bdbd356db732b30d0a5',
    messagingSenderId: '1010169881408',
    projectId: 'vcroad-a0022',
    authDomain: 'vcroad-a0022.firebaseapp.com',
    storageBucket: 'vcroad-a0022.firebasestorage.app',
    measurementId: 'G-B115VW2NV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3BcNF1piKBkBtNCCAVLHTqDtY0lveHBI',
    appId: '1:1010169881408:android:7b6064a12395ab0d30d0a5',
    messagingSenderId: '1010169881408',
    projectId: 'vcroad-a0022',
    storageBucket: 'vcroad-a0022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnh8CupQFByOi1eDVSz7jr8_UPeClxaaE',
    appId: '1:1010169881408:ios:196d13294473ef8d30d0a5',
    messagingSenderId: '1010169881408',
    projectId: 'vcroad-a0022',
    storageBucket: 'vcroad-a0022.firebasestorage.app',
    iosBundleId: 'com.example.vcroad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnh8CupQFByOi1eDVSz7jr8_UPeClxaaE',
    appId: '1:1010169881408:ios:196d13294473ef8d30d0a5',
    messagingSenderId: '1010169881408',
    projectId: 'vcroad-a0022',
    storageBucket: 'vcroad-a0022.firebasestorage.app',
    iosBundleId: 'com.example.vcroad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtsj7f5QCvU-aKQhdQB2RBGyZ_iE0lFa8',
    appId: '1:1010169881408:web:162de8c97603891c30d0a5',
    messagingSenderId: '1010169881408',
    projectId: 'vcroad-a0022',
    authDomain: 'vcroad-a0022.firebaseapp.com',
    storageBucket: 'vcroad-a0022.firebasestorage.app',
    measurementId: 'G-LK5S7EB6X2',
  );
}
